language: go
go:
  - 1.11.x
  - 1.12.x
notifications:
  email: false

# Cache compiled Vim.
cache:
  directories:
    - '$HOME/vim'

matrix:
  include:
    - env: 'VIM_VERSION=v8.0.1630'
    - env: 'NVIM_VERSION=v0.3.2'

install: |
  # Use Python 3
  pyenv global 3.7

  # Move plugin to more logical location.
  cd ~
  mkdir -p ~/.vim/pack/plugin/start
  mv "$TRAVIS_BUILD_DIR" ~/.vim/pack/plugin/start
  ln -s ~/.vim/pack/plugin/start/* "$TRAVIS_BUILD_DIR"

  # Install Vim or Neovim if there it doesn't exist yet.
  if [ ! -e "$HOME/vim/bin/vim" ]; then
    # Neovim
    if [ "${NVIM_VERSION:-}" != "" ]; then
      curl -Ls https://github.com/neovim/neovim/releases/download/$NVIM_VERSION/nvim-linux64.tar.gz | tar xzf - -C /tmp/
      rm -r "$HOME/vim"
      mv "/tmp/nvim-linux64"  "$HOME/vim"
      mv "$HOME/vim/bin/nvim" "$HOME/vim/bin/vim"
    # Vim
    else
      git clone -q --depth 1 --branch "$VIM_VERSION" https://github.com/vim/vim $HOME/vim-src
      ( cd $HOME/vim-src && ./configure --prefix $HOME/vim --with-features=huge --disable-gui )
      ( cd $HOME/vim-src && make install )
    fi
  fi

  # Install vint.
  pip3 install -q vim-vint covimerage codecov

  # Clone testing.vim
  git clone -q --depth 1 https://github.com/arp242/testing.vim.git ~/testing.vim

script: |
  set -e
  cd "$HOME/.vim/pack/plugin/start/$(basename "$TRAVIS_BUILD_DIR")"
  export TEST_VIM="$HOME/vim/bin/vim"
  $HOME/testing.vim/tvim test -p coverage.xml ./...
  $HOME/testing.vim/tvim lint ./...

after_success: |
  set -e
  cd "$HOME/.vim/pack/plugin/start/$(basename "$TRAVIS_BUILD_DIR")"
  codecov -X search gcov pycov -f coverage.xml
